### ISSUE TITLE
using sass?

### ISSUE THREAD

**Issue by persianphilosopher** [codyogden/press-css#1]
Love this project. So clean, so simple, but so powerful. Very nice job!

It runs great when I clone the repo, run yarn and then node-sass does its job perfectly. 
Running ```sass press.scss``` however throws:
```
Error: 2.4 is not an integer.
        on line 6 of _functions.scss
  Use --trace for backtrace.
```
I am not sure if it's on purpose that it only works with node-sass. In my workflow, I rely on the gem sass. Is there a way to make this work with just sass itself?

Thanks again for an awesome library.

**Comment by codyogden** [comment]
Thank you for submitting an issue! I resolved the issue with gem sass, and it should be working correctly on `Sass 3.5.1 (Bleeding Edge)`.
