### ISSUE TITLE
suggestion: group buttons

### ISSUE THREAD

**Issue by persianphilosopher** [codyogden/press-css#2]
Thanks again for this lovely collection. 
I am wondering if you would consider adding group buttons to the lot. In particular, there is a button that I have used from Semantic-UI that is really nice, [the conditional button](https://semantic-ui.com/elements/button.html#conditionals) that is this *or* that. [Foundation has took that idea too](http://foundation.zurb.com/building-blocks/blocks/button-group-option.html) which is neat because they supply the scss file and Semantic does not. 
Just a thought. Thank you!

**Comment by persianphilosopher** [comment]
Even though Foundation provides the scss files, it is not easy to just extract the needed material. These days, scss files are quite helpful though. 

[Just to show, I combined the css (not scss) of Foundation and Press CSS in codepen.](https://codepen.io/persianphilosopher/details/Ojjwdd/)

I did not tweak any of the Foundation source. I did change the class ```.press``` to ```.button``` to make it work.  Although it looks ok, it lacks that touch of finess that Press CSS brings, especially in the "or" and the white space around it.

**Comment by codyogden** [comment]
Hello again,

Thanks for your suggestion. I am very happy you like this project. It truly means a lot!!

I tend to view Press.css through the lens of [Atomic Design](http://bradfrost.com/blog/post/atomic-web-design/). The project is an Atom which can be incorporated into other Molecules and Organisms. In other words, Press.css buttons should be the most basic unit available to include something bigger. But this suggestion did allow me to put Press.css (as an Atomic design Atom) to the test!

So, I set out to create the button group Molecule like the examples using Press Atoms. Here is [a CodePen](https://codepen.io/codyogden/pen/eEELEE/) and a [Gist](https://gist.github.com/codyogden/aecf2730dedc0db2f71e5fedff4c9ca9) of it working .

I'll file this request for future reference should the project begin to grow into a more complete UI system. For now, it's only an Atoms!
