### ISSUE TITLE
Likely dev dependency missing

### ISSUE THREAD

**Issue by persianphilosopher** [codyogden/press-css#6]
Hi @codyogden:

Sorry to be the one bugging you again. This issue is somewhat related to #1 but I think there are some differences that it's worth opening a new one. 

**The problem using the repo**: After cloning, I have tried to compile the scss files by running:
* sass(gem)
* yarn/npm run build/dev (from local package.json)
* node-sass (global)

In all cases, the output has this problem with every color, but here is the snippet for red:

```.press {
    box-sizing: border-box;
    background-color: var(--p);
    border: 2px solid var(--p);
    color: var(--c);
    cursor: pointer;
    display: inline-block;
    font-size: 1em;
    margin: 0;
    padding: 0.5em 0.75em;
    text-align: center;
    text-decoration: none;
    transition: background 0.15s linear; }
.press-red {
    --p: #F44336;
    --c: if( $testContrast, press_test_contrast($hex, $textColor), $textColor );
    --h: #f55a4e;
    --a: #ea1c0d; }
```
I can provide the rest of the output but it's just the same issue with each color. 

**The problem using npm**:  Using ```npm install press-css```, after I install everything from package.json, the output is exactly as above. 

**The odd case of yarn **  yarn does not work if starting with the cloned repo but ```yarn add press-css``` _does_ work. 

Both yarn and npm download the older package.json, before your recent trim. It's likely a requirement that's now missing. But I don't know why ```npm install press-css``` still fails, even with the old package.json. 

*Versions*: node v8.11.3, npm v6.1.0, yarn 1.7.0, Sass 3.5.5 (Bleeding Edge). Tested on both Ubuntu and Windows. 

Anyway, hopefully this provides enough information for you. Thank you again for a fantastic package.

**Comment by codyogden** [comment]
Hey! I'll take a closer look this weekend. I think I know the issue. Thanks!
